steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/mineralogy-rocks/mr-nuxt:latest || exit 0
  - name: gcr.io/cloud-builders/docker
    timeout: 1200s
    args:
      [
        'build',
        '-f',
        'Dockerfile',
        '-t',
        'gcr.io/mineralogy-rocks/mr-nuxt',
        '--cache-from',
        'gcr.io/mineralogy-rocks/mr-nuxt:latest',
        '.',
      ]
timeout: 1200s
images:
  - gcr.io/mineralogy-rocks/mr-nuxt
